// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RedVital.Campanas.Infraestructura.Persistencia;

#nullable disable

namespace RedVital.Campanas.Infraestructura.Persistencia.Migrations
{
    [DbContext(typeof(CampanasDbContext))]
    partial class CampanasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RedVital.Campanas.Dominio.Campania", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizada_en");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<Guid>("CreadaPor")
                        .HasColumnType("uuid")
                        .HasColumnName("creada_por");

                    b.Property<int>("CupoReservado")
                        .HasColumnType("integer")
                        .HasColumnName("cupo_reservado");

                    b.Property<int?>("CupoTotal")
                        .HasColumnType("integer")
                        .HasColumnName("cupo_total");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("IniciaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicia_en");

                    b.Property<Guid>("InstitucionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institucion_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset?>("PublicadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicada_en");

                    b.Property<string>("Sede")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sede");

                    b.Property<DateTimeOffset>("TerminaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("termina_en");

                    b.Property<string>("TerritorioCodigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("territorio_codigo");

                    b.Property<string>("TerritorioRuta")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("territorio_ruta");

                    b.HasKey("Id");

                    b.HasIndex("Estado", "TerminaEn");

                    b.ToTable("campania", null, t =>
                        {
                            t.HasCheckConstraint("ck_campania_estado", "estado IN ('borrador', 'publicada', 'cerrada', 'cancelada')");

                            t.HasCheckConstraint("ck_campania_fechas", "termina_en > inicia_en");
                        });
                });

            modelBuilder.Entity("RedVital.Campanas.Dominio.RegistroAuditoriaCamp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_tipo");

                    b.Property<string>("CorrelacionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("correlacion_id");

                    b.Property<string>("JurisdiccionSolicitada")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("jurisdiccion_solicitada");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operacion");

                    b.Property<string>("Origen")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("origen");

                    b.Property<Guid?>("RecursoId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurso_id");

                    b.Property<string>("RecursoTipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("recurso_tipo");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("resultado");

                    b.Property<string>("Rol")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("CorrelacionId");

                    b.HasIndex("OcurridoEn");

                    b.ToTable("registro_auditoria_camp", null, t =>
                        {
                            t.HasCheckConstraint("ck_auditoria_camp_actor_tipo", "actor_tipo IN ('usuario', 'sistema', 'anonimo')");

                            t.HasCheckConstraint("ck_auditoria_camp_resultado", "resultado IN ('permitido', 'denegado')");
                        });
                });

            modelBuilder.Entity("RedVital.Campanas.Dominio.ReservaCupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaniaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campania_id");

                    b.Property<DateTimeOffset?>("CerradaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cerrada_en");

                    b.Property<DateTimeOffset?>("ConfirmadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmada_en");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CampaniaId");

                    b.HasIndex("Estado", "ExpiraEn");

                    b.ToTable("reserva_cupo", null, t =>
                        {
                            t.HasCheckConstraint("ck_reserva_estado", "estado IN ('pendiente', 'confirmada', 'liberada', 'cancelada')");
                        });
                });

            modelBuilder.Entity("RedVital.Campanas.Dominio.ReservaCupo", b =>
                {
                    b.HasOne("RedVital.Campanas.Dominio.Campania", "Campania")
                        .WithMany("Reservas")
                        .HasForeignKey("CampaniaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campania");
                });

            modelBuilder.Entity("RedVital.Campanas.Dominio.Campania", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
