// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RedVital.Identidad.Infraestructura.Persistencia;

#nullable disable

namespace RedVital.Identidad.Infraestructura.Persistencia.Migrations
{
    [DbContext(typeof(IdentidadDbContext))]
    [Migration("20261002070114_InicialIdentidad")]
    partial class InicialIdentidad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RedVital.Identidad.Dominio.CredencialServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cliente");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<DateTimeOffset?>("RotadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotada_en");

                    b.Property<string>("SecretoHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("secreto_hash");

                    b.HasKey("Id");

                    b.HasIndex("Cliente")
                        .IsUnique();

                    b.ToTable("credencial_servicio", null, t =>
                        {
                            t.HasCheckConstraint("ck_credencial_servicio_cliente", "cliente IN ('gateway', 'donacion', 'notificaciones')");
                        });
                });

            modelBuilder.Entity("RedVital.Identidad.Dominio.Rol", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("AmbitoAdmitido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ambito_admitido");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("perfil");

                    b.HasKey("Codigo");

                    b.ToTable("rol", (string)null);

                    b.HasData(
                        new
                        {
                            Codigo = "donante",
                            AmbitoAdmitido = "ninguno",
                            Perfil = "U2 — Donante registrado"
                        },
                        new
                        {
                            Codigo = "operador",
                            AmbitoAdmitido = "institucion (exactamente una)",
                            Perfil = "U3 — Operador de banco"
                        },
                        new
                        {
                            Codigo = "admin_banco",
                            AmbitoAdmitido = "institucion (exactamente una)",
                            Perfil = "U4 — Administrador de banco"
                        },
                        new
                        {
                            Codigo = "coordinador",
                            AmbitoAdmitido = "territorio departamental o municipal, uno o varios",
                            Perfil = "U5 — Coordinador territorial"
                        },
                        new
                        {
                            Codigo = "admin_nacional",
                            AmbitoAdmitido = "territorio nacional",
                            Perfil = "U6 — Administrador nacional"
                        },
                        new
                        {
                            Codigo = "auditor",
                            AmbitoAdmitido = "territorio nacional, lectura limitada",
                            Perfil = "U7 — Auditor"
                        });
                });

            modelBuilder.Entity("RedVital.Identidad.Dominio.Sesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EmitidaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emitida_en");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("MotivoRevocacion")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("motivo_revocacion");

                    b.Property<string>("Origen")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("origen");

                    b.Property<DateTimeOffset?>("RenovadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("renovada_en");

                    b.Property<DateTimeOffset?>("RevocadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocada_en");

                    b.Property<string>("SecretoHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("secreto_hash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sesion", null, t =>
                        {
                            t.HasCheckConstraint("ck_sesion_motivo_revocacion", "motivo_revocacion IS NULL OR motivo_revocacion IN ('cierre', 'desactivacion', 'cambio_rol', 'cambio_jurisdiccion', 'reutilizacion', 'rotacion_emergencia')");
                        });
                });

            modelBuilder.Entity("RedVital.Identidad.Dominio.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CredencialHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("credencial_hash");

                    b.Property<string>("Nombre")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("RolCodigo")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol_id");

                    b.Property<DateTimeOffset?>("UltimoAccesoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso_en");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("RolCodigo");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("RedVital.Identidad.Dominio.UsuarioJurisdiccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ambito");

                    b.Property<Guid>("AsignadaPor")
                        .HasColumnType("uuid")
                        .HasColumnName("asignada_por");

                    b.Property<Guid?>("InstitucionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institucion_id");

                    b.Property<string>("TerritorioCodigo")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("territorio_codigo");

                    b.Property<string>("TerritorioRuta")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("territorio_ruta");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTimeOffset>("VigenteDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_desde");

                    b.Property<DateTimeOffset?>("VigenteHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_hasta");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuario_jurisdiccion", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuario_jurisdiccion_ambito", "ambito IN ('territorio', 'institucion')");
                        });
                });

            modelBuilder.Entity("RedVital.Identidad.Dominio.Sesion", b =>
                {
                    b.HasOne("RedVital.Identidad.Dominio.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RedVital.Identidad.Dominio.Usuario", b =>
                {
                    b.HasOne("RedVital.Identidad.Dominio.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("RedVital.Identidad.Dominio.UsuarioJurisdiccion", b =>
                {
                    b.HasOne("RedVital.Identidad.Dominio.Usuario", "Usuario")
                        .WithMany("Jurisdicciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RedVital.Identidad.Dominio.Usuario", b =>
                {
                    b.Navigation("Jurisdicciones");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
